### ISSUE TITLE
Rules Not Updated after modifying in Preferences Panel.

### ISSUE THREAD

**Issue by wenyaoliu** [windingwind/zotero-tag#35] opened 2022-08-05 16:52 UTC
Thanks for developing this fantastic add-on. 

I am using Zotero 6.10 and zotero-tag
![image](https://user-images.githubusercontent.com/94808374/183123980-42ff1e81-aef7-484a-8a27-d1f068527df3.png)

![image](https://user-images.githubusercontent.com/94808374/183123894-2926d185-9be4-4ccc-a119-b18335b89abc.png)

I found one issue that every time I modify the rules following the instructed steps, the modified rules works after zotero restarts. However, when I open the preference the Rules were not updated and made me confusion. 

![image](https://user-images.githubusercontent.com/94808374/183123715-a30b3712-dfca-4c53-9907-5e8b96d27af6.png)

**Comment by windingwind** [comment] 2022-09-04 09:43
Are you using any other plugins, like the Zotero If series?
This is a bug caused by that plugin, which is confict to many other plugins. It's close-source thus I cannot help.

**Comment by VladimirAlexiev** [comment] 2022-09-29 10:28
@wenyaoliu What do you see in Tools>Developer>Error Console?

**Comment by windingwind** [comment] 2022-11-08 06:13
Since there is no reply for weeks, I'll close this issue.
Please feel free to open it again.

**Closed by windingwind** 2022-11-08 06:13 UTC
